site_name: SURNUMERISM
site_url: https://surnumerisme.com
theme:
  name: material
  language: en
  favicon: favicon.png   # <-- ajout du favicon
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Chapters:
      - Chapter 1: chapters/chapter1.md
      - Chapter 2: chapters/chapter2.md
      - Chapter 3: chapters/chapter3.md
  - About: about.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - tables
  - attr_list
